repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: "v2.0.4"
    hooks:
      - id: autopep8
        args: ['--global-config', '.flake8']
        additional_dependencies: ['flake8==7.0.0']

  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: ['--config=.flake8']

  - repo: https://github.com/nbQA-dev/nbQA
    rev: "1.8.5"
    hooks:
      - id: nbqa-pyupgrade
        args: ["--py37-plus"]
      - id: nbqa-isort
        args: ["--float-to-top"]
